services:
  redis:
    env_file:
      - path: ./.env.redis
        required: false
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    command: /bin/sh -c "redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru --loglevel warning --requirepass $$REDIS_HOST_PASSWORD"

  backend:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    build: 
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: node build/src/server.js
    ports:
      - "8080:8080"
    env_file: 
      - path: ./.env
        required: false
    environment:
      - AWS_REGION=${AWS_REGION}
    volumes: !reset []
