up: 
	docker compose -f compose.dev.yaml up -d


up-prod:
	docker-compose -f compose.dev.yaml -f compose.prod.yaml up --build -d


build-dev:
	docker compose -f compose.dev.yaml build --no-cache


down:
	docker compose -f compose.dev.yaml down
