import {
  TAIPEI_CITY,
  NEW_TAIPEI_CITY,
  KEELUNG_CITY,
  TAOYUAN_CITY,
  HSINCHU_CITY,
  HSINCHU_COUNTY,
  MIAOLI_COUNTY,
  TAICHUNG_CITY,
  NANTOU_COUNTY,
  CHANGHUA_COUNTY,
  YUNLIN_COUNTY,
  CHIAYI_CITY,
  CHIAYI_COUNTY,
  TAINAN_CITY,
  KAOHSIUNG_CITY,
  PINGTUNG_COUNTY,
  YILAN_COUNTY,
  HUALIEN_COUNTY,
  TAITUNG_COUNTY,
  PENGHU_COUNTY,
  KINMEN_COUNTY,
  LIENCHIANG_COUNTY,
  RAW_LOCATION,
  DISTRICT,
} from "./enum";

export const TAIPEI_CITY_API = {
  [TAIPEI_CITY.DATONG]: "204",
  [TAIPEI_CITY.GUTING]: "202",
  [TAIPEI_CITY.SHILIN]: "199",
  [TAIPEI_CITY.SONGSHAN]: "203",
  [TAIPEI_CITY.WANHUA]: "201",
  [TAIPEI_CITY.YANGMING]: "251",
  [TAIPEI_CITY.ZHONGSHAN]: "200",
};

export const NEW_TAIPEI_CITY_API = {
  [NEW_TAIPEI_CITY.BANQIAO]: "194",
  [NEW_TAIPEI_CITY.CAILIAO]: "196",
  [NEW_TAIPEI_CITY.FUGUEICAPE]: "461",
  [NEW_TAIPEI_CITY.LINKOU]: "197",
  [NEW_TAIPEI_CITY.SANCHONG]: "254",
  [NEW_TAIPEI_CITY.SHULIN]: "",
  [NEW_TAIPEI_CITY.TAMSUI]: "198",
  [NEW_TAIPEI_CITY.TUCHENG]: "193",
  [NEW_TAIPEI_CITY.XINDIAN]: "192",
  [NEW_TAIPEI_CITY.XINZHUANG]: "195",
  [NEW_TAIPEI_CITY.XIZHI]: "190",
  [NEW_TAIPEI_CITY.YONGHE]: "257",
};

export const KEELUNG_CITY_API = {
  [KEELUNG_CITY.KEELUNG]: "189",
};

export const TAOYUAN_CITY_API = {
  [TAOYUAN_CITY.DAYUAN]: "206",
  [TAOYUAN_CITY.GUANYIN]: "207",
  [TAOYUAN_CITY.LONGTAN]: "209",
  [TAOYUAN_CITY.PINGZHEN]: "208",
  [TAOYUAN_CITY.TAOYUAN]: "205",
  [TAOYUAN_CITY.ZHONGLI]: "255",
};

export const HSINCHU_CITY_API = {
  [HSINCHU_CITY.HSINCHU]: "212",
};

export const HSINCHU_COUNTY_API = {
  [HSINCHU_COUNTY.HUKOU]: "210",
  [HSINCHU_COUNTY.ZHUDONG]: "211",
};

export const MIAOLI_COUNTY_API = {
  [MIAOLI_COUNTY.MIAOLI]: "214",
  [MIAOLI_COUNTY.SANYI]: "215",
  [MIAOLI_COUNTY.TOUFEN]: "213",
};

export const TAICHUNG_CITY_API = {
  [TAICHUNG_CITY.DALI]: "218",
  [TAICHUNG_CITY.FENGYUAN]: "216",
  [TAICHUNG_CITY.SHALU]: "217",
  [TAICHUNG_CITY.TAIWAN_AVENUE]: "",
  [TAICHUNG_CITY.XITUN]: "220",
  [TAICHUNG_CITY.ZHONG_MING]: "219",
};

export const NANTOU_COUNTY_API = {
  [NANTOU_COUNTY.LUGU]: "",
  [NANTOU_COUNTY.NANTOU]: "224",
  [NANTOU_COUNTY.PULI]: "259",
  [NANTOU_COUNTY.ZHUSHAN]: "256",
};

export const CHANGHUA_COUNTY_API = {
  [CHANGHUA_COUNTY.CHANGHUA]: "221",
  [CHANGHUA_COUNTY.DACHENG]: "",
  [CHANGHUA_COUNTY.ERLIN]: "223",
  [CHANGHUA_COUNTY.XIANXI]: "222",
  [CHANGHUA_COUNTY.YUANLIN]: "",
};

export const YUNLIN_COUNTY_API = {
  [YUNLIN_COUNTY.DOULIU]: "225",
  [YUNLIN_COUNTY.LUNBEI]: "226",
  [YUNLIN_COUNTY.MAILIAO]: "264",
  [YUNLIN_COUNTY.TAIXI]: "229",
};

export const CHIAYI_CITY_API = {
  [CHIAYI_CITY.CHIAYI]: "230",
};

export const CHIAYI_COUNTY_API = {
  [CHIAYI_COUNTY.PUZI]: "228",
  [CHIAYI_COUNTY.XINGANG]: "227",
};

export const TAINAN_CITY_API = {
  [TAINAN_CITY.ANNAN]: "233",
  [TAINAN_CITY.LINSEN]: "",
  [TAINAN_CITY.SHANHUA]: "232",
  [TAINAN_CITY.TAINAN]: "234",
  [TAINAN_CITY.XINYING]: "231",
};

export const KAOHSIUNG_CITY_API = {
  [KAOHSIUNG_CITY.DALIAO]: "239",
  [KAOHSIUNG_CITY.FENGSHAN]: "238",
  [KAOHSIUNG_CITY.FUXING]: "258",
  [KAOHSIUNG_CITY.LINYUAN]: "240",
  [KAOHSIUNG_CITY.MEINONG]: "235",
  [KAOHSIUNG_CITY.NANZI]: "241",
  [KAOHSIUNG_CITY.QIANJIN]: "243",
  [KAOHSIUNG_CITY.QIANZHEN]: "244",
  [KAOHSIUNG_CITY.QIAOTOU]: "236",
  [KAOHSIUNG_CITY.RENWU]: "237",
  [KAOHSIUNG_CITY.XIAOGANG]: "245",
  [KAOHSIUNG_CITY.ZUOYING]: "242",
};

export const PINGTUNG_COUNTY_API = {
  [PINGTUNG_COUNTY.CHAOZHOU]: "247",
  [PINGTUNG_COUNTY.FANGSHAN]: "",
  [PINGTUNG_COUNTY.HENGCHUN]: "248",
  [PINGTUNG_COUNTY.LIUQIU]: "",
  [PINGTUNG_COUNTY.PNGTUNG]: "246",
};

export const YILAN_COUNTY_API = {
  [YILAN_COUNTY.DONGSHAN]: "253",
  [YILAN_COUNTY.YILAN]: "252",
};

export const HUALIEN_COUNTY_API = {
  [HUALIEN_COUNTY.HUALIEN]: "250",
};

export const TAITUNG_COUNTY_API = {
  [TAITUNG_COUNTY.GUANSHAN]: "263",
  [TAITUNG_COUNTY.TAITUNG]: "249",
};

export const PENGHU_COUNTY_API = {
  [PENGHU_COUNTY.MAGONG]: "262",
};

export const KINMEN_COUNTY_API = {
  [KINMEN_COUNTY.KINMEN]: "261",
};

export const LIENCHIANG_COUNTY_API = {
  [LIENCHIANG_COUNTY.MATSU]: "260",
};

export const LOCATION_API = {
  ...TAIPEI_CITY_API,
  ...NEW_TAIPEI_CITY_API,
  ...KEELUNG_CITY_API,
  ...TAOYUAN_CITY_API,
  ...HSINCHU_CITY_API,
  ...HSINCHU_COUNTY_API,
  ...MIAOLI_COUNTY_API,
  ...TAICHUNG_CITY_API,
  ...NANTOU_COUNTY_API,
  ...CHANGHUA_COUNTY_API,
  ...YUNLIN_COUNTY_API,
  ...CHIAYI_CITY_API,
  ...CHIAYI_COUNTY_API,
  ...TAINAN_CITY_API,
  ...KAOHSIUNG_CITY_API,
  ...PINGTUNG_COUNTY_API,
  ...YILAN_COUNTY_API,
  ...HUALIEN_COUNTY_API,
  ...TAITUNG_COUNTY_API,
  ...PENGHU_COUNTY_API,
  ...KINMEN_COUNTY_API,
  ...LIENCHIANG_COUNTY_API,
};

export const DISTRICT_LOOKUP: Record<RAW_LOCATION, DISTRICT> = {
  [RAW_LOCATION.TAIPEI_CITY]: DISTRICT.TAIPEI_CITY,
  [RAW_LOCATION.NEW_TAIPEI_CITY]: DISTRICT.NEW_TAIPEI_CITY,
  [RAW_LOCATION.KEELUNG_CITY]: DISTRICT.KEELUNG_CITY,
  [RAW_LOCATION.TAOYUAN_CITY]: DISTRICT.TAOYUAN_CITY,
  [RAW_LOCATION.HSINCHU_CITY]: DISTRICT.HSINCHU_CITY,
  [RAW_LOCATION.HSINCHU_COUNTY]: DISTRICT.HSINCHU_COUNTY,
  [RAW_LOCATION.MIAOLI_COUNTY]: DISTRICT.MIAOLI_COUNTY,
  [RAW_LOCATION.TAICHUNG_CITY]: DISTRICT.TAICHUNG_CITY,
  [RAW_LOCATION.NANTOU_COUNTY]: DISTRICT.NANTOU_COUNTY,
  [RAW_LOCATION.CHANGHUA_COUNTY]: DISTRICT.CHANGHUA_COUNTY,
  [RAW_LOCATION.YUNLIN_COUNTY]: DISTRICT.YUNLIN_COUNTY,
  [RAW_LOCATION.CHIAYI_CITY]: DISTRICT.CHIAYI_CITY,
  [RAW_LOCATION.CHIAYI_COUNTY]: DISTRICT.CHIAYI_COUNTY,
  [RAW_LOCATION.TAINAN_CITY]: DISTRICT.TAINAN_CITY,
  [RAW_LOCATION.KAOHSIUNG_CITY]: DISTRICT.KAOHSIUNG_CITY,
  [RAW_LOCATION.PINGTUNG_COUNTY]: DISTRICT.PINGTUNG_COUNTY,
  [RAW_LOCATION.YILAN_COUNTY]: DISTRICT.YILAN_COUNTY,
  [RAW_LOCATION.HUALIEN_COUNTY]: DISTRICT.HUALIEN_COUNTY,
  [RAW_LOCATION.TAITUNG_COUNTY]: DISTRICT.TAITUNG_COUNTY,
  [RAW_LOCATION.PENGHU_COUNTY]: DISTRICT.PENGHU_COUNTY,
  [RAW_LOCATION.KINMEN_COUNTY]: DISTRICT.KINMEN_COUNTY,
  [RAW_LOCATION.LIENCHIANG_COUNTY]: DISTRICT.LIENCHIANG_COUNTY,
};
