export type Location =
  | TAIPEI_CITY
  | NEW_TAIPEI_CITY
  | KEELUNG_CITY
  | TAOYUAN_COUNTY
  | HSINCHU_CITY
  | HSINCHU_COUNTY
  | MIAOLI_COUNTY
  | TAICHUNG_CITY
  | NANTOU_COUNTY
  | CHANGHUA_COUNTY
  | YUNLIN_COUNTY
  | CHIAYI_CITY
  | CHIAYI_COUNTY
  | TAINAN_CITY
  | KAOHSIUNG_CITY
  | PINGTUNG_COUNTY
  | YILAN_COUNTY
  | HUALIEN_COUNTY
  | TAITUNG_COUNTY
  | PENGHU_COUNTY
  | KINMEN_COUNTY
  | LIENCHIANG_COUNTY;

export enum TAIPEI_CITY {
  ZHONGSHAN = "ZHONGSHAN",
  YANGMING = "YANGMING",
  DATONG = "DATONG",
  SONGSHAN = "SONGSHAN",
  GUTING = "GUTING",
  WANHUA = "WANHUA",
  SHILIN = "SHILIN",
}

export enum NEW_TAIPEI_CITY {
  SHULIN = "SHULIN",
  FUGUEICAPE = "FUGUEICAPE",
  YONGHE = "YONGHE",
  SANCHONG = "SANCHONG",
  TAMSUI = "TAMSUI",
  LINKOU = "LINKOU",
  CAILIAO = "CAILIAO",
  XINZHUANG = "XINZHUANG",
  BANQIAO = "BANQIAO",
  TUCHENG = "TUCHENG",
  XINDIAN = "XINDIAN",
  XIZHI = "XIZHI",
}

export enum KEELUNG_CITY {
  KEELUNG = "KEELUNG",
}

export enum TAOYUAN_COUNTY {
  ZHONGLI = "ZHONGLI",
  LONGTAN = "LONGTAN",
  PINGZHEN = "PINGZHEN",
  GUANYIN = "GUANYIN",
  DAYUAN = "DAYUAN",
  TAOYUAN = "TAOYUAN",
}

export enum HSINCHU_CITY {
  HSINCHU = "HSINCHU",
}

export enum HSINCHU_COUNTY {
  ZHUDONG = "ZHUDONG",
  HUKOU = "HUKOU",
}

export enum MIAOLI_COUNTY {
  SANYI = "SANYI",
  MIAOLI = "MIAOLI",
  TOUFEN = "TOUFEN",
}

export enum TAICHUNG_CITY {
  TAIWAN_AVENUE = "TAIWAN_AVENUE",
  XITUN = "XITUN",
  ZHONG_MING = "ZHONG_MING",
  DALI = "DALI",
  SHALU = "SHALU",
  FENGYUAN = "FENGYUAN",
}

export enum NANTOU_COUNTY {
  PULI = "PULI",
  ZHUSHAN = "ZHUSHAN",
  NANTOU = "NANTOU",
  LUGU = "LUGU",
}

export enum CHANGHUA_COUNTY {
  YUANLIN = "YUANLIN",
  DACHENG = "DACHENG",
  ERLIN = "ERLIN",
  XIANXI = "XIANXI",
  CHANGHUA = "CHANGHUA",
}

export enum YUNLIN_COUNTY {
  MAILIAO = "MAILIAO",
  TAIXI = "TAIXI",
  LUNBEI = "LUNBEI",
  DOULIU = "DOULIU",
}

export enum CHIAYI_CITY {
  CHIAYI = "CHIAYI",
}

export enum CHIAYI_COUNTY {
  PUZI = "PUZI",
  XINGANG = "XINGANG",
}

export enum TAINAN_CITY {
  LINSEN = "LINSEN",
  TAINAN = "TAINAN",
  ANNAN = "ANNAN",
  SHANHUA = "SHANHUA",
  XINYING = "XINYING",
}

export enum KAOHSIUNG_CITY {
  FUXING = "FUXING",
  XIAOGANG = "XIAOGANG",
  QIANZHEN = "QIANZHEN",
  QIANJIN = "QIANJIN",
  ZUOYING = "ZUOYING",
  NANZI = "NANZI",
  LINYUAN = "LINYUAN",
  DALIAO = "DALIAO",
  FENGSHAN = "FENGSHAN",
  RENWU = "RENWU",
  QIAOTOU = "QIAOTOU",
  MEINONG = "MEINONG",
}

export enum PINGTUNG_COUNTY {
  FANGSHAN = "FANGSHAN",
  LIUQIU = "LIUQIU",
  HENGCHUN = "HENGCHUN",
  CHAOZHOU = "CHAOZHOU",
  PNGTUNG = "PINGTUNG",
}

export enum YILAN_COUNTY {
  DONGSHAN = "DONGSHAN",
  YILAN = "YILAN",
}

export enum HUALIEN_COUNTY {
  HUALIEN = "HUALIEN",
}

export enum TAITUNG_COUNTY {
  TAITUNG = "TAITUNG",
  GUANSHAN = "GUANSHAN",
}

export enum PENGHU_COUNTY {
  MAGONG = "MAGONG",
}

export enum KINMEN_COUNTY {
  KINMEN = "KINMEN",
}

export enum LIENCHIANG_COUNTY {
  MATSU = "MATSU",
}

export enum Pollutant {
  PARTICULATE_MATTER_TWO_POINT_FIVE = "PM2.5",
  PARTICULATE_MATTER_TEN = "PM10",
  NITOGEN_DIOXIDE = "NO2",
  OZONE = "O3",
  CARBON_MONOXIDE = "CO",
  SULFUR_DIOXIDE = "SO2",
}
